# Generated by Django 4.1.13 on 2025-10-25 16:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentmodel",
            name="roll_no",
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
